name: "default"
origin: "https://raw.githubusercontent.com/traberph/getgit/refs/heads/main/config/sources.d/default.yaml"

repos:
  - name: "getgit"
    url: "traberph/getgit"
    build: "make build"
    executable: "bin/getgit"
    
    

